version: '3.8'

services:

  jupyter:
    image: opendatacube/cube-in-a-box:latest
    container_name: jupyter
    environment:
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      # Defaults are defined in .env file
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REQUEST_PAYER: ${AWS_REQUEST_PAYER}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      # Talk to AWS without using credentials
      AWS_NO_SIGN_REQUEST: "${AWS_NO_SIGN_REQUEST}"
      CIABPASSWORD: ${CIABPASSWORD:-secretpassword}
    ports:
      - "80:8888"
    volumes:
    #  - ../deafrica-sandbox-notebooks:/notebooks    
    #  - ./notebooks:/notebooks
      - ../cube-in-a-box/notebooks:/notebooks
    #  - ./products.csv:/products.csv
    restart: always
    command: "jupyter notebook --allow-root --ip='0.0.0.0' -NotebookApp.token='${CIABPASSWORD}'"


networks: 
  default: 
    external: 
      name: odcnet
