version: '3.8'

services:

  ows:
    image: opendatacube/ows:latest
    container_name: ows
    ports:
      - 8000:8000
    environment:
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      PYTHONPATH: /env/config
      DATACUBE_OWS_CFG: ows_refactored.dev_af_ows_root_cfg.ows_cfg
      # Defaults are defined in .env file
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REQUEST_PAYER: ${AWS_REQUEST_PAYER}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      # Talk to AWS without using credentials
      AWS_NO_SIGN_REQUEST: "${AWS_NO_SIGN_REQUEST}"
    volumes:
      - ./services/ows_refactored:/env/config/ows_refactored/
      - ./services/inventory:/env/config/inventory/
      - /data/odc/ows/output:/env/config/output/


networks: 
  default: 
    external: 
      name: odcnet