version: '3.8'

services:
  postgres:
    image: postgis/postgis:14-3.2-alpine
    container_name: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /data/odc/pg/data:/var/lib/postgresql/data      
    restart: always

  products-tester:
    image: opendatacube/datacube-index:latest 
    container_name: products-tester
    environment:
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - postgres
    volumes:
      - ./dev/products_dev.csv:/conf/products_dev.csv
      - ./prod/products_prod.csv:/conf/products_prod.csv
    command: tail -f /dev/null 


networks: 
  default: 
    external: 
      name: odcnet